name: Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up workflow with Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: Set environment variables
        id: set-env
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            echo "SERVER_IP=TODO_IP_ADDRESS" >> $GITHUB_ENV
          else
            echo "SERVER_IP=TODO_DEV_IP_ADDRESS" >> $GITHUB_ENV
          fi

      # TODO: Update all environment values below for your project
      - name: Create .env file
        run: |
          echo "ENVIRONMENT=prod" >> .env
          echo "NEXT_PUBLIC_SITE_NAME=sol" >> .env
          echo "NEXT_PUBLIC_SITE_BASE_DOMAIN=https://sol.grav.solutions" >> .env
          echo "SITE_DOMAIN=sol.grav.solutions" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DJANGO_SETTINGS_MODULE=settings" >> .env
          echo "POSTGRES_DB=soldb" >> .env
          echo "POSTGRES_USER=soluser" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "EMAIL_HOST=smtp.sendgrid.net" >> .env
          echo "EMAIL_HOST_USER=apikey" >> .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
          echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> .env

      - name: Create Django static directory
        run: |
          cd ./web
          pip install -r requirements.txt
          python manage.py collectstatic --noinput

      - name: Expose SSH key
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy-key.pem
          else
            echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" > deploy-key.pem
          fi
          chmod 400 deploy-key.pem

      - name: Sync files with server
        run: |
          rsync -r --delete --progress --exclude-from=exclude.txt -e "ssh -i $(pwd)/deploy-key.pem -o StrictHostKeyChecking=no" . ubuntu@${{ env.SERVER_IP }}:app

      - name: SSH into server; rebuild Docker containers
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            ssh -i $(pwd)/deploy-key.pem ubuntu@${{ env.SERVER_IP }} 'cd app && docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up --build -d'
          else
            ssh -i $(pwd)/deploy-key.pem ubuntu@${{ env.SERVER_IP }} 'cd app && docker compose -f docker-compose.yaml -f docker-compose.staging.yaml up --build -d'
          fi

      - name: Remove SSH key
        run: |
          rm -f deploy-key.pem
